frontend/src/components/Configuration/DroneConfiguration.jsx
Draft pull request. So far both of the drones have the same models. I will work on getting the new commented drone models added to the fixed wing drone.
=> Drone Model Dropdown

frontend/src/components/EnvironmentConfiguration.jsx
Here is my draft pull request for the wind origin and wind type. I have made constant wind the first option in the environment configuration file. On top of that, I have made the turbulent wind have another choice of fluctuation percentage. The shear wind portion needs to be implemented.
=> Issue9 add wind originfor wind type

frontend/src/components/EnvironmentConfiguration.jsx
Made it so that three checkboxes show up after the fuzzy tester is clicked. It is implemented so that there always needs to be one enabled.
=> Made working product of fuzzy testing checkboxes

frontend/src/components/Configuration/SensorsConfiguration/Barometer.jsx, frontend/src/components/Configuration/SensorsConfiguration/GPS.jsx
=> Issue24-Up To Date GPS details

backend/PythonClient/multirotor/control/simulation_task_manager.py, backend/PythonClient/server/simulation_server.py, frontend/src/components/EnvironmentConfiguration.jsx, frontend/src/pages/Home.jsx
Allows the user to see the backend status on the frontend UI. The status bar is located in the Environment configuration portion of the UI. When there is no backend connected, it will turn red with an error. When it is connected to the backend but there is no simulation running, it will be green and show an idle status. When there is a simulation running, it will turn blue with running status. The number of tasks queued will also be displayed.
=> Issue40 api integrationfor simulation status

frontend/src/components/ReportDashboard.jsx
UI Update — Checkmark or X for dashboard on Acceptance test report page fetch API from backend for status
=> beginning stages of acceptance ui changes

frontend/src/App.js, frontend/src/LandingPage.jsx, frontend/src/components/AboutUs.jsx, frontend/src/components/LandingPage.jsx, frontend/src/components/ReportDashboard.jsx, frontend/src/styles.css
=> Landing Page

frontend/src/components/Configuration/SensorsConfiguration/Barometer.jsx, frontend/src/components/Configuration/SensorsConfiguration/Magnetometer.jsx
Made it so the sensors correctly parse the data as floats and not as strings. GPS is fixed in another branch which needs to be merged
=> Fixed parsing bug

frontend/src/LandingPage.jsx, frontend/src/pages/Home.jsx
Added the card for the About Us page. It is temporarily stored on the Home page with a button that says to delete it later and link to it from the Nav bar.
=> About Us Page Card

frontend/src/components/EnvironmentConfiguration.jsx
Only testing if Turbulent Wind is fixed. If so I will work on Wind sheer
=> Turbulent Wind and Wind Sheer

frontend/src/LandingPage.jsx, frontend/src/components/ReportDashboard.jsx, frontend/src/styles.css
just starting link. link to issue #18 also completed in this pull request (2 issues in 1).
=> linking dashboard and landing page

frontend/src/components/EnvironmentConfiguration.jsx
Fixed #99 
React app crashes when given an incomplete time format
I fixed the issue, by using the dayjs library, which automatically error-checks incomplete information
such as ie (10:00:00) is complete however (10:00) is incomplete as we are missing the seconds, this thus causes a null exception, my fix stops this issue
=> fixed the issue, used the dayjs library

backend/PythonClient/multirotor/airsim_application.py, backend/requirements.txt
This PR modifies a couple of files in preparation for the integration of Google Cloud Storage (GCS) for uploading reports. The changes include setting up configurations and ensuring the project is ready for the upcoming GCS implementation.
=> Prepare files for GCS implementation

.github/workflows/backend-ci.yml, .github/workflows/frontend-ci.yml
Add two new workflows, one for backend and one for frontend.
=> Create workflows for testing

backend/PythonClient/multirotor/mission/abstract/abstract_mission.py, backend/PythonClient/multirotor/monitor/abstract/globa_monitor.py, backend/PythonClient/multirotor/monitor/abstract/single_drone_mission_monitor.py
Made a small adjustment to update the report-saving logic in the relevant mission and monitor files.
=> Update GCS client

.github/workflows/backend-ci.yml, backend/PythonClient/multirotor/airsim_application.py, backend/PythonClient/multirotor/monitor/point_deviation_monitor.py, backend/PythonClient/multirotor/storage/__init__.py, backend/PythonClient/multirotor/storage/gd_storage_service.py, backend/PythonClient/multirotor/storage/gsc_storage_service.py, backend/PythonClient/multirotor/util/graph/three_dimensional_grapher.py, backend/requirements.txt
- **Reset of point_deviation_monitor.py and three_dimensional_grapher.py**
- `three_dimensional_grapher.py` needs to be refactored to facilitate the upload of HTML and PNG files.
- `point_deviation_monitor.py` should not be handling direct handles file uploads.
- **Modifications to airsim_application.py and Creation of storage/_\_init__.py**
- Simplified the import process for new storage services.
- Streamlined the initialization process for storage services.
- **Creation of `gd_storage_service.py`**
- Established the foundational setup for a new Google Drive storage service.
- **Updated `requirements.txt`**
- Added support for Google Drive integration.
=> Update Files for Sprint 5

frontend/src/LandingPage.jsx, frontend/src/components/ReportDashboard.jsx, frontend/src/pages/Home.jsx
- I have added a loader in the report dashboard that only comes up when the reports are loading(placeholder)
- Do not show the snackbar(No report found) until the reports is successfully loaded
- Do not show the button `Return to Home` until the reports are done loading
However;
With present logic, I think the loader on the landing page is necessary as the reports are also being fetched and displayed on the homepage(if there are reports). However, I have adjusted design and removed one of the duplicated button saying `Create Simulation`
Please kindly review.
Thanks
=> add loader in report dashboard

backend/PythonClient/server/simulation_server.py, frontend/src/components/Dashboard.jsx, frontend/src/components/FuzzyDashboard.jsx
#145 
Currently, with fall break I had less time than I would've liked. I was able to track down the error and figure out what I will need to do, but It will take a bit of time to fully implement the goal.
More specifically, the error exists when the backend attempts to route through to the front end using react location states. An issue can occur where the files being sent as a report back to the front end are not routing properly and are therefore detected as non-existent. However, this can happen for several reasons: the router fails, the file is not created, the file is the wrong type, or the file is incomplete.
I have to go through and make sure these different errors are reported and accounted for with the react-router.
I have to read the React documentation to find out the best …
=> violation error 

backend/PythonClient/multirotor/storage/gcs_storage_service.py, backend/PythonClient/multirotor/storage/gd_storage_service.py
#174 
Implemented two methods list_reports() and get_report_content(). This is to allow for retrieving files and folders from google drive. 
This is needed to allow for better Google Drive functionality as well. 
Currently list_reports has been implemented and there is also a method called test_reports() to test if it is working correctly. There is also a test-reports endpoint in order to see the metadata contents of the folder such as whats done with the gcs storage. As of my testing this method does what it is supposed to do. 
Get_report_content is a method used to retrieve specific files from google drive. Currently this method has been coded as well, but there is alot of debugging to be done in order to get the desired result. There is also a test_get_report_content method that …
=> Issue174WIP

frontend/src/components/EnvironmentConfiguration.jsx, frontend/src/contexts/MainJsonContext.js, frontend/src/utils/regionUtils.js
fixes #185
Modified the EnvironmentConfiguration.jsx file to ensure that useEffect triggers backend updates whenever there are changes to wind settings, region origin, and time of day. I also added in the files MainJsonContext.js and regionUtils.js from the private repo as a foundation to ultimately implement the drag-and-drop feature functionality.
These files were brought in to ensure useMainJson is properly synchronizing with the backend, and it needs the region location and drone location files for accurate simulation setup. This should ultimately allow for the user to drag a drone icon into the cesium map (still needs to be implemented) and accurately begin the simulation from there, alone with environmental settings.
The file structure was updated to align with the private repo, …
=> 185 data sync with useMainJson

frontend/src/components/cesium/CesiumMap.jsx, frontend/src/components/cesium/DroneDragAndDrop.jsx, frontend/src/model/EnvironmentModel.js
fixes #192 
Removed the comments for the ImageURLS, as Val's pull request finishes most of that implementation
This was changed to fit the goal of fixing Drag and Drop for the UI.
This change was to allow for images to be loaded into the UI.
very simple change, hopefully process will work. with these actions, will attempt fix tomorrow if it does not.
=> Resolve imageUrls import and upload related images #192

frontend/babel.config.js, frontend/craco.config.js, frontend/package.json, frontend/src/App.js, frontend/src/CesiumMap.jsx, frontend/src/components/cesium/DrawSadeZone.jsx, frontend/src/components/cesium/RegionDragAndDrop.jsx, frontend/src/components/cesium/TimeLineSetterCesiumComponent.jsx, frontend/src/contexts/MainJsonContext.js, frontend/src/utils/const.js, frontend/src/utils/mapUtils.js
fixes #198 
Cesium is now rendered in its own path /cesium-map. To my knowledge it works correctly. However, it still needs to be rendered inside of wizard. 
This was needed in order to progress towards adding a drag and drop feature using real time maps. 
Currently, everything works as intended, but there are a few issues rendering inside Wizard.jsx currently such as possibly a missing save state, to be worked on.
=> Integrated React in Cesium-map path, wizard TBD

frontend/src/components/Configuration/MissionConfiguration.jsx
Fixes #206 
Removed local droneArray state and uses MainJsonContext instead. Also added some functionality in the setdrone function in order to make sure new drones are added to the arrary and are pushed to MainJson. 
This was needed in order to keep track of the drones and their state when multiple are added to the map. There still needs to be a way to identify the drones once on the map i.e. a letter, name or unique identifier. 
My issue should work once merged with Valerie's single drone implementation. This was all needed in order to complete our Drag and Drop functionality.
=> Fixes the multiple drone drag and drog error

frontend/src/components/Configuration/MissionConfiguration.jsx
fixes #222 
Added Null Checks and Comments to the handle drone decrement function. 
This was needed to prevent possible errors and to ensure future workers on this project are able to understand what the code means.
=> Added comments and null checks

frontend/src/components/Configuration/DroneConfiguration.jsx
Fixes#221
The drone sync location logic was improved to ensure the drone icon moves live on cesium map when the user changes the values in the respective text boxes.
Originally, the drone's X, Y, and Z coordinates were not synced with mainJson, causing the drone to not update its position in the Cesium Map. 
Calling droneJson updates the Latitude and Longitude of the new location. syncDroneLocation now updates the local state and notifies parent of changes.
=> Fixes #221 Drone Lat. and Long. Update on Cesium

pixelstreaming.md, start_enviroment.ps1
#213 
Added markdown explaining the local changes required for pixel streaming to work
Added start_enviroment.ps1
This when ran automatically creates the proper virtual environment, installs all requirements, installs all npm requirements, creates the AirSim folder in Documents, then runs the backend and front end automatically, This can be used instead of doing all of this manually, and can be ran after setup and it will automatically skip setting up the install of the venv,  
[Previous pull](https://github.com/oss-slu/DroneWorld/pull/216)
Use This as a reference for updating pixel streaming to be automatic, this can be added as a in the frontend, and perhaps as an addendum to the PowerShell script.
Further, adding automatic unreal detection and start up with the block,exe could be …
=> clean push of pixel streaming and start_enviroment.ps1
